package uk.gov.companieshouse.filinghistory.consumer.service;

import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

@Component
public class FormTypeService {

    private static final String ANNOTATION_FORM_TYPE = "ANNOTATION";
    private static final String ASSOCIATED_FILING_FORM_TYPE = "ASSOCIATED-FILING";
    private static final String TOP_LEVEL_FORM_TYPE = "TOP-LEVEL";
    private static final List<String> FORM_TYPE_BLACKLIST = List.of(
            "1(Scot)",
            "1(scot)",
            "1(SC)",
            "1.1",
            "1.1(NI)",
            "1.1(Scot)",
            "1.1(SC)",
            "1.11",
            "1.11(Scot)",
            "1.11(SC)",
            "1.12",
            "1.12(Scot)",
            "1.12(SC)",
            "1.14",
            "1.14(Scot)",
            "1.14(SC)",
            "1.2",
            "1.3",
            "1.3(NI)",
            "1.3(Scot)",
            "1.3(SC)",
            "1.4",
            "1.4(NI)",
            "1.4(Scot)",
            "1.4(SC)",
            "12.1",
            "2(Scot)",
            "2(scot)",
            "2.11B(Scot)",
            "2.11B(SC)",
            "2.12B",
            "2.12B(NI)",
            "2.15B(Scot)",
            "2.15B(SC)",
            "2.16B",
            "2.16B(NI)",
            "2.16B(Scot)",
            "2.16B(SC)",
            "2.16BZ(Scot)",
            "2.16BZ(SC)",
            "2.17B",
            "2.17B(NI)",
            "2.17B(Scot)",
            "2.17B(SC)",
            "2.18B",
            "2.18B(NI)",
            "2.18B(Scot)",
            "2.18B(SC)",
            "2.18BA(NI)",
            "2.19",
            "2.19B(Scot)",
            "2.19B(SC)",
            "2.20B(Scot)",
            "2.20B(SC)",
            "2.21B(Scot)",
            "2.21B(SC)",
            "2.22B",
            "2.22B(NI)",
            "2.22B(Scot)",
            "2.22B(SC)",
            "2.23B",
            "2.23B(NI)",
            "2.23B(Scot)",
            "2.23B(SC)",
            "2.24B",
            "2.24B(NI)",
            "2.24B(Scot)",
            "2.24B(SC)",
            "2.25B(Scot)",
            "2.25B(SC)",
            "2.26B",
            "2.26B(NI)",
            "2.27B",
            "2.28B",
            "2.2B(Scot)",
            "2.2B(SC)",
            "2.30B",
            "2.30B(NI)",
            "2.31B",
            "2.31B(NI)",
            "2.31B(Scot)",
            "2.31B(SC)",
            "2.32B",
            "2.32B(NI)",
            "2.32B(Scot)",
            "2.32B(SC)",
            "2.33B",
            "2.33B(NI)",
            "2.34B",
            "2.34B(NI)",
            "2.40B",
            "2.40B(NI)",
            "2.7",
            "3.05(NI)",
            "3.07(NI)",
            "3.08(NI)",
            "3.12(NI)",
            "3.3",
            "3.4",
            "3.5(Scot)",
            "3.5(scot)",
            "3.5(SC)",
            "3.6",
            "39C(NI)",
            "4.10",
            "4.13",
            "4.15",
            "4.2(Scot)",
            "4.2(SC)",
            "4.20",
            "4.21(NI)",
            "4.27(Scot)",
            "4.27(SC)",
            "4.31",
            "4.31(Scot)",
            "4.31(SC)",
            "4.32(NI)",
            "4.44(NI)",
            "4.48",
            "4.48(NI)",
            "4.49(NI)",
            "4.51",
            "4.68",
            "4.69",
            "4.69(NI)",
            "4.70",
            "4.71(NI)",
            "4.9(Scot)",
            "4.9(SC)",
            "49(8)a",
            "49(8)b",
            "405(1)",
            "558(NI)",
            "600",
            "703P(5)",
            "ADD IN ADMIN",
            "AM01",
            "AM01(Scot)",
            "AM02",
            "AM02(Scot)",
            "AM03",
            "AM03(Scot)",
            "AM04",
            "AM05",
            "AM06",
            "AM06(Scot)",
            "AM07",
            "AM07(Scot)",
            "AM08",
            "AM09",
            "AM10",
            "AM11",
            "AM12",
            "AM19",
            "AM20",
            "AM21",
            "AM22",
            "AM25",
            "CERT8A",
            "CO4.2(Scot)",
            "CO4.2(SC)",
            "COCOMP",
            "COM1",
            "COM2",
            "COM3",
            "COM4",
            "CVA1",
            "CVA3",
            "CVA4",
            "CVA1(Scot)",
            "CVA2(Scot)",
            "CVA3(Scot)",
            "CVA4(Scot)",
            "DETERMINAT",
            "DETERMINAT(NI)",
            "DETERM(NI)",
            "EC REGS F",
            "EC_REGS_F",
            "F10.2",
            "F14",
            "F2.18",
            "F9.4",
            "L22(NI)",
            "LIQ MISC",
            "LIQ MISC OC",
            "LIQ MISC OC(NI)",
            "LIQ MISC OC(NI)",
            "LIQ MISC RES",
            "LIQ MISC(NI)",
            "LIQ MISCRES(NI)",
            "LIQMISC",
            "LIQMISCNIO",
            "LIQMISCRES",
            "LIQMISC(NI)",
            "LIQMISCRES(NI)",
            "LIQ01",
            "LIQ02",
            "LIQ03",
            "LLNM01",
            "LLRM01",
            "LQ01",
            "LRES(NI)",
            "LRESC(NI)",
            "LRESEX",
            "LRESM(NI)",
            "LRESSP",
            "NDISC",
            "NOCP",
            "O/C STAY",
            "O/C_STAY",
            "O/C UNSTAY",
            "O/C_UNSTAY",
            "OCRESCIND",
            "OSDS02",
            "OSLQ01",
            "OSLQ02",
            "OSLQ03",
            "OSLQ04",
            "REC2",
            "RM01",
            "VAM7",
            "VL1",
            "WU04",
            "WU07",
            "CERT10",
            "CERT3",
            "MAR",
            "RES02",
            "RES06",
            "49(1)",
            "49(8)(a)",
            "49(8)(b)",
            "53",
            "(W)ELRES",
            "ELRES",
            "ERES01",
            "ERES03",
            "ERES04",
            "ERES06",
            "ERES07",
            "ERES08",
            "ERES09",
            "ERES10",
            "ERES11",
            "ERES12",
            "ERES13",
            "ERES14",
            "ORES01",
            "ORES03",
            "ORES04",
            "ORES05",
            "ORES06",
            "ORES07",
            "ORES08",
            "ORES09",
            "ORES10",
            "ORES11",
            "ORES12",
            "ORES13",
            "ORES14",
            "RES01",
            "RES03",
            "RES 03",
            "RES04",
            "RES05",
            "RES07",
            "RES08",
            "RES09",
            "RES10",
            "RES 10",
            "RES11",
            "RES12",
            "RES13",
            "RES 13",
            "RES14",
            "RES16",
            "SRES01",
            "SRES02",
            "SRES03",
            "SRES04",
            "SRES05",
            "SRES06",
            "SRES07",
            "SRES08",
            "SRES09",
            "SRES10",
            "SRES11",
            "SRES12",
            "SRES13",
            "SRES14",
            "SRES16",
            "WRES01",
            "WRES02",
            "WRES03",
            "WRES04",
            "WRES05",
            "WRES06",
            "WRES07",
            "WRES08",
            "WRES09",
            "WRES10",
            "WRES11",
            "WRES12",
            "WRES13",
            "WRES14",
            "RR01",
            "RR02",
            "RR04",
            "RR05",
            "RR06",
            "RR07",
            "RR08",
            "RR09",
            "RR10",
            "AUDR",
            "AUDS",
            "BS",
            "CERT1",
            "CERT11",
            "CERT2",
            "CERT22",
            "CERT23",
            "CERT24",
            "CERT4",
            "CERT5",
            "CERT7",
            "FOA-RR",
            "RRFOA",
            "RROC138",
            "RROC649",
            "VAL",
            "RP04SH01",
            "RP04SH02",
            "RP04SH05",
            "RP04SH06",
            "RP04SH07",
            "RP04SH14",
            "RP04SH15",
            "MT01",
            "MT02",
            "MT03",
            "MT04",
            "MT05",
            "MT06",
            "MT07",
            "MT08",
            "MT09"
    );

    public String getFormType(TransactionKindCriteria transactionKindCriteria) {
        final String deltaParentFormType = transactionKindCriteria.parentFormType();
        final String deltaFormType = transactionKindCriteria.formType();
        final String parentEntityId = transactionKindCriteria.parentEntityId();

        final String formType;

        if (ANNOTATION_FORM_TYPE.equals(deltaParentFormType)) {
            formType = ANNOTATION_FORM_TYPE;
        } else if (isAssociatedFiling(deltaParentFormType, deltaFormType, parentEntityId)) {
            formType = ASSOCIATED_FILING_FORM_TYPE;
        } else {
            formType = TOP_LEVEL_FORM_TYPE;
        }
        return formType;
    }

    private boolean isAssociatedFiling(final String deltaParentFormType,
                                       final String deltaFormType,
                                       final String parentEntityId) {
        final boolean isAssociatedFiling;

        // TODO: Check for null/empty form types?

        if (FORM_TYPE_BLACKLIST.contains(deltaParentFormType) || FORM_TYPE_BLACKLIST.contains(deltaFormType)) {
            isAssociatedFiling = false;
        } else isAssociatedFiling = StringUtils.isNotBlank(parentEntityId);
        return isAssociatedFiling;
    }
}
